defaults: &defaults
  docker:
    - image: cimg/node:16.14.0-browsers
      environment:
        CHROME_BIN: '/usr/bin/google-chrome'
  working_directory: ~/repo

version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: sudo npm install -g pnpm@8.15.4

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Install Dependencies
          command: pnpm install

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - checkout_code
